---
- name: Playbook with the register keyword
  hosts: futurama

  tasks:
    - name: "Issue a command"
      command: ls /lib/
      register: contentz_lib

    - name: "debug - display data returned"
      debug: 
        msg: "{{ contentz_lib  }}"

    - name: "debug - std error"
      debug:
        msg "{{ contentz_lib.stderr  }}"

    - name: "debug - std out"
      debug:
        msg "{{ contentz_lib.stdout  }}"

